// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { ase, Database } from './types';

const SUPABASE_URL = "https://ykkjjcaqvtdoyikhfivl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlra2pqY2FxdnRkb3lpa2hmaXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODUwNzcsImV4cCI6MjA2ODA2MTA3N30.49uBlmWwES9tyL0rSshaNIVwe-2CDP0P9ywl8EJvdWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
